{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge.gradle",
    "module": "ForgeGradle",
    "version": "6.10.47",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-6.10.47.jar",
          "url": "ForgeGradle-6.10.47.jar",
          "size": 490951,
          "sha512": "dde11895491ba98df8d0bbe1f1b5eeefeda6d8c59668c52d2f49ac6dcf5e9afeb444da986d55193742b7b1cab6d12275bdb8ea1b8789907797d18411880dba4b",
          "sha256": "ce867c557371d65fc445e9b22efe6f61d714133b4436db8d24090f45a27a1fc1",
          "sha1": "c6dce16c71111d7055e26e84acc38e0d7ac7d9f3",
          "md5": "2d285592d2d6eee1b1bbcbc475ad77ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.10"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-6.10.47.jar",
          "url": "ForgeGradle-6.10.47.jar",
          "size": 490951,
          "sha512": "dde11895491ba98df8d0bbe1f1b5eeefeda6d8c59668c52d2f49ac6dcf5e9afeb444da986d55193742b7b1cab6d12275bdb8ea1b8789907797d18411880dba4b",
          "sha256": "ce867c557371d65fc445e9b22efe6f61d714133b4436db8d24090f45a27a1fc1",
          "sha1": "c6dce16c71111d7055e26e84acc38e0d7ac7d9f3",
          "md5": "2d285592d2d6eee1b1bbcbc475ad77ad"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-6.10.47-sources.jar",
          "url": "ForgeGradle-6.10.47-sources.jar",
          "size": 213849,
          "sha512": "5820a2d6df4d688ca9d076d5a6d84895bd7666481cd3b4b03b97433608837b916008138460dca46b9e7fdb58a92305ed522d8cc00652c0c2eb69c07590a77edb",
          "sha256": "60b73be55499ad074d6deff5a61d8718cb8af18a708444f2e8addedd7e3cc219",
          "sha1": "daadde3ebcb0fbb94a5d0ca088778979f2210bd4",
          "md5": "46cfd053cfa04bf9a601e6da04598fe9"
        }
      ]
    }
  ]
}
