{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge.gradle",
    "module": "ForgeGradle",
    "version": "6.10.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-6.10.43.jar",
          "url": "ForgeGradle-6.10.43.jar",
          "size": 490904,
          "sha512": "500d31f4256760febe436a23f9d2ce91704506d0828b3be8db1c2829f4c4fc2a28fe7a8520bd36deda63171a17ed72f3aeb3ffac17430c8c6155b56e656e066f",
          "sha256": "bea991097b236def3c80fb1b083f364abe639930f91686375083ea0aad7dd5d8",
          "sha1": "b9ff6bc802425b83b6cfdba5c282f199e4d71be6",
          "md5": "5f036a2576b0a415b043e22e94811e41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.11.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.2.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "3.0.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "unsafe",
          "version": {
            "requires": "0.2.0"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.9.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.14"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.5.10"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarMetadata",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "JarJarSelector",
          "version": {
            "requires": "0.3.19"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-6.10.43.jar",
          "url": "ForgeGradle-6.10.43.jar",
          "size": 490904,
          "sha512": "500d31f4256760febe436a23f9d2ce91704506d0828b3be8db1c2829f4c4fc2a28fe7a8520bd36deda63171a17ed72f3aeb3ffac17430c8c6155b56e656e066f",
          "sha256": "bea991097b236def3c80fb1b083f364abe639930f91686375083ea0aad7dd5d8",
          "sha1": "b9ff6bc802425b83b6cfdba5c282f199e4d71be6",
          "md5": "5f036a2576b0a415b043e22e94811e41"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeGradle-6.10.43-sources.jar",
          "url": "ForgeGradle-6.10.43-sources.jar",
          "size": 213828,
          "sha512": "00ef4dd2216d62cec5a55fc627fec5a9b686791a3b72c8d6aff2978cfce90e3c4d25502c7d87e0458bd258c5cd71ce1661992bbdb3f72f8fdb62e71d08c63e09",
          "sha256": "535400909cc86aa9be8acfd63085c9e9b2bae45003708b0f8a1a7f28caaa2f67",
          "sha1": "894005dc068dc294630d90e17cea17232ea7bde4",
          "md5": "89b0d475e06f215026baa03de6b3095c"
        }
      ]
    }
  ]
}
